---
title: "Course Introduction and Schedule"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Course at a glance

* Monday/Wednesday class at 7:00 pm China time (see Slack for Zoom class link)
* Tuesday lab 8:30-11:00 am China time in AB Seminar 1A 1079 
* Office hours -  
  + Monday, Wednesday 2:00-4:00 pm China time in CC2064 or by Zoom
  + Friday 9:00-11:00 am China time (Zoom only)
* Pre-class warmup quiz due at 7:00 pm before each class
* Homeworks are all due on Sunday at 11:59 pm
* All other announcements and information are posted on the class Slack

# Course description

How can we use data to shed light on age-old and new human problems such as pollution, discrimination, and economic growth? How can we be “sure” that the evidence we have points us in the right direction? How meaningful are our findings? Do our results suggest the relationships we find between factors such smoking and cancer are meaningful or meaningless? How would we know? How should one properly display and explain your statistical results to these important issues?

This class introduces you to the tools and concepts that begin to tackle these questions. We will cover topics such as data summaries, sampling, data analysis, production of graphical displays, and regression techniques. The goal at the end of the course is that you will be able to conduct basic data manipulation, know how to properly summarize and display data, and make basic statistical inferences using real datasets. 

The emphasis in the course will not be on learning mathematical formulas related to statistics but rather to develop an intuitive understanding of statistical inference and measures of uncertainty. For those interested in developing this intuitive understanding of statistics in a more rigorous way, you may also consider taking the following courses:

* Math 205: the mathematical foundations of statistics
* Econ 203: advanced study of modern regression techniques
* Social Sciences 350: advanced statistical techniques applied to real-world problems

A third set of goals for the course is that you will also be able to read more fluently research literature that employs statistics. During this course I will reference, in class, a number of historically important academic articles and we will analyze the data from those articles. Doing so should help you understand how data is used (and misused) to construct social science arguments.

# Course schedule

Important: class schedule is subject to change, contingent on mitigating circumstances and the progress we make as a class. If there are any changes, I will announce them on Slack.

## Unit 1: Distributions

### Monday, January 10th: Class Welcome

Reading to do before class: Chapter 1, 2.1 and 2.2, and 3

Topics covered:

-	What are data and variables?
-	How to display quantitative and qualitative variables
-	Contingency tables

### Wednesday, January 12th: Characteristics of Distributions

Reading to do before class: Chapter 2.3-5 and 4

> Syllabus & preclass quiz due at 7:00 pm China time

Topics covered:

- How to describe the shape, center, and spread of a distribution
- How to compare distributions
- Dealing with problem distributions (outliers, reexpression)

>**Labs due on Friday, January 14th @ 11:59 pm China time:** 
>
>1. [Introduction to R](https://learn.datacamp.com/courses/free-introduction-to-r)
>2. [Introduction to the Tidyverse](https://learn.datacamp.com/courses/introduction-to-the-tidyverse)

### Monday, January 17th: The Normal Distribution

Reading to do before class: Chapter 5

> Preclass quiz due at 7:00 pm China time

Topics covered:

- Standard deviation and standardizing values
- Normal models
- Normal percentiles

## Unit 2: Relationships Between Variables

### Wednesday, January 19th: Association and Correlation

Reading to do before class: Chapter 6

> Preclass quiz due at 7:00 pm China time

Topics covered:

- Scatterplots
- Correlations
- Does correlation imply causation?

>**Labs due on Friday, January 21st at 11:59 pm China time:**  
>
>- [Exploratory Data Analysis in R](https://learn.datacamp.com/courses/exploratory-data-analysis-in-r) 
>- [Introduction to Data Visualization with ggplot2](https://learn.datacamp.com/courses/introduction-to-data-visualization-with-ggplot2) 

>**[Homework 1](https://sakai.duke.edu/x/fNZCcj) due Sunday, January 23rd at 11:59 pm China time**

### Monday, January 24th: Simple Linear Regression

Reading to do before class: Chapter 7

> Preclass quiz due at 7:00 pm China time

Topics covered:

- Line of best fit: least squares
- The linear model
- What are residuals
- Regression assumptions

### Wednesday, January 26th: Regression Wisdom

Reading to do before class: Chapter 8

> Preclass quiz due at 7:00 pm China time China time

Topics covered:

- Beware extrapolation
- Outliers and leverage
- Lurking variables
- Straightening scatterplots

>**Labs due on Friday, January 28th at 11:59 pm China time:** 
>
>- [Correlation and Regression in R](https://learn.datacamp.com/courses/correlation-and-regression-in-r)

>**[Midterm progress check](https://sakai.duke.edu/x/fNZCcj) due Sunday, January 30th at 11:59 pm China time**

*** Chinese New Year holiday from January 29th-February 6th***

### Monday, February 7th: Multiple Regression

Reading to do before class: Chapter 9

> Preclass quiz due at 7:00 pm China time

Topics covered:

- What is multiple regression?
- Interpreting multiple regression coefficients
- Partial regression plots
- Indicator variables

## Unit 3: Measuring Uncertainty

### Wednesday, February 9th: Confidence Intervals - Proportions

Reading to do before class: Chapter 13

> Preclass quiz due at 7:00 pm China time

Topics covered:

- What is a sampling distribution?
- When does the normal model apply?
- Constructing a confidence interval
- Interpreting a confidence interval

>**Lab due on Friday, February 11th at 11:59 pm China time:** 
>
>- [Multiple and Logistic Regression in R, chapters 1, 2, 3 and 5](https://learn.datacamp.com/courses/multiple-and-logistic-regression-in-r)

**[Midterm Project](https://sakai.duke.edu/x/fNZCcj) due on Sunday, February 13th at 11:59 pm China time**

### Monday, February 14th: Confidence Intervals - Means

Reading to do before class: Chapter 14

> Preclass quiz due at 7:00 pm China time

Topics covered:

- The Central Limit Theorem
- Confidence interval for means
- Interpreting a confidence interval
- Final thoughts on confidence intervals

### Wednesday, February 16th: Hypothesis Testing

Reading to do before class: Chapter 15

> Preclass quiz due at 7:00 pm China time

Topics covered:

- What are hypotheses?
- P-values
- P-values and decisions – how to make a decision

>**Lab due on Friday, September 24nd at 11:59 pm China time:** 
>
>- [Inference for Categorical Data in R, chapters 1, 2](https://learn.datacamp.com/courses/inference-for-categorical-data-in-r)

>**[Homework 2 check](https://sakai.duke.edu/x/fNZCcj) due Sunday, February 20th at 11:59 pm China time**

### Monday, February 21st: Hypothesis Testing Wisdom

Reading to do before class: Chapter 16

> Preclass quiz due at 7:00 pm China time

Topics covered:

- Interpreting p-values
- Alpha and critical values
- Practical vs. statistical significance
- Type I and II errors
- Power of a test

## Unit 4: Statistical Inference

### Wednesday, February 23rd: Comparing Groups

Reading to do before class: Chapter 17

> Preclass quiz due at 7:00 pm China time

Topics covered:

- Confidence intervals for comparing two samples
- Assumptions and conditions for two-sample hypothesis tests
- Two-sample z test
- Two-sample t test

>**Lab due on Friday, February 25th at 11:59 pm China time:** 
>
>- [Foundations of Inference, chapters 1, 2, and 3](https://learn.datacamp.com/courses/foundations-of-inference-in-r)

>**[Homework 2](https://sakai.duke.edu/x/fNZCcj) due Sunday, February 27th at 11:59 pm China time**

### Monday, February 28th: Returning to Regression

Reading to do before class: Chapter 20

> Preclass quiz due at 7:00 pm China time

Topics covered:

- Regression inference and intuition
- The regression table
- Confidence and prediction intervals

### Wednesday, March 2nd: Regression in Practice

Reading to do before class: TBD

> No preclass quiz

Topics covered:

- How to read academic statistical results
- Locating the model
- Interpreting the test
- Understanding possible weaknesses of the model

>**Lab due on Friday, March 4th at 11:59 pm China time:**  
>
>- [Inference for Linear Regression in R](https://learn.datacamp.com/courses/inference-for-linear-regression-in-r)

>**[Paper Analysis](https://sakai.duke.edu/x/fNZCcj) due Sunday, March 6th at 11:59 pm China time**


>**[Final Project](https://sakai.duke.edu/x/fNZCcj) due on Thursday, March 10th at 11:59 pm China Time**
