---
title: "Lecture & Lab Materials"
author: "Andrew MacDonald"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lectures

## Unit 1: Distributions

### Class Welcome

* Recording: [Class 1](https://duke.zoom.us/rec/share/P63Iyay_3X-RQ1aixtu4xV0cYVllbvh8KyYrpqEY0sglGTBt7hFMOh2YeF6-5HNR.kNFMe07lvFiQW3Rb?startTime=1641811488000)

### Characteristics of Distributions

* Lecture webpage: [Characteristics of distributions](https://andrewm.shinyapps.io/spr2022distributions) 
* Recording: [Class 2](https://duke.zoom.us/rec/share/-ZCftywyQVABVGi3myZHE3S-Dry3RV-diMDomS2-m1V_m5tA2ibQms7zF-MSerBL.KA0UhVWsOAejLJSD?startTime=1641984674000)
* Quality YouTube content: [Tidyverse music video](https://www.youtube.com/watch?v=p8Py9C8iq2s&ab_channel=TheRaf)

### Comparing distributions and the Normal distribution

* Lecture webpage: [Advanced distributions](https://andrewm.shinyapps.io/spr2022advanceddistributions/)
* Recording: [Class 3](https://duke.zoom.us/rec/share/XxjQSOejfWjRibeiQTTljfoOd8okrgmiRRS9bVFzWlmtUsOwQEOwhZk1fTg1W0-e.ofozZZ1JiknM6TEq?startTime=1642416412000)

## Unit 2: Relationships Between Variables

### Association and Correlation

* Lecture webpage: [Association and correlation](https://andrewm.shinyapps.io/spr2022association/)
* Recording: [Class 4](https://duke.zoom.us/rec/share/AtrlFuAlWsJlcWkHJ_5E_ZCxqN9i5Ye7PMHLUxtGvMc4ISNK-P22lkgvavxBY5ok.-3wn3tFAcYr08WiE?startTime=1642589659000)

### Simple Linear Regression

* Lecture webpage: [Simple linear regression](https://andrewm.shinyapps.io/spr2022simpleregression/)
* Recording: [Class 5](https://duke.zoom.us/rec/share/47sjFFlJubTm5FDii_5RVt_nNiVf0auQjDTTwdeHRgn6qaApDkto-pD3cboQtXNG.xBapqGn3f1mYYf2H?startTime=1643021638000)

### Regression Wisdom

* Lecture webpage: [Regression wisdom](https://andrewm.shinyapps.io/spr2022regressionwisdom/)
* Recording: [Class 6](https://duke.zoom.us/rec/share/1lrWijzPrrS5BAh_saWi21jlAtw_9oIILSx-4x-uJU9P29r14gRhv36mIMnZNyNm.uyNTvSpHVBcdf58D?startTime=1643194206000)

### Multiple Regression

* Lecture webpage: [Multiple regression](https://andrewm.shinyapps.io/spr2022multipleregression/) 
* Recording: [Class 7](https://duke.zoom.us/rec/share/Qc7X7W0a04lT7-AxtwYccF0bHTeDf-6dHG8sfBwDhAUcVZhvSlCkHaSmx6cJm4XW.I-cnLGi5IaNp4Hio?startTime=1644231216000)

## Unit 3: Measuring Uncertainty

### Confidence Intervals - Proportions

* Lecture webpage: [Confidence intervals - proportions](https://andrewm.shinyapps.io/spr2022confintprop/)
* Recording: [Class 8](https://duke.zoom.us/rec/share/pxtjQoSHpgYlKKGgu1sOylGSuhHSXNipa5D7JFgtMUifI10iPB3ENPpOTTzHzvGt.BcHQIFgqS1lHV096
)

### Confidence Intervals - Means

* Lecture webpage: [Confidence intervals - means](https://andrewm.shinyapps.io/spr2022confintmean/)
* Recording: [Class 9](https://duke.zoom.us/rec/share/_gXqcr66EtMFASBqcEBJQTr63NGdeHMmpVle1SMKsuhajvQaACwhDV1KiaWJ9k5t.SO_rJ2rPSBMbHu9V?startTime=1644835735000)

### Hypothesis Testing

* Lecture webpage: 
* Recording: 

### Hypothesis Testing Wisdom

* Lecture webpage: 
* Recording: 

## Unit 4: Statistical Inference

### Comparing Groups

* Lecture webpage: 
* Recording: 

### Returning to Regression

* Lecture webpage: 
* Recording: 

# Labs

## Week 1: R and RMarkdown

* Lab files: [Lab 1 - R Markdown](labs/wk1/lab1.zip)
  + Make sure to extract (unzip) the lab files before attempting to modify them!

## Week 2: Exploratory Data Analysis

* Lab files: [Lab 2 - Exploratory Data Analysis](labs/wk2/lab2.zip)

## Week 3: Regression Interpretation

* Lab files: [Lab 3 - Association and Correlation](labs/wk3/lab3.zip)

## Week 4: Model Building

* Lab files [Lab 4 - Model Building](labs/wk4/lab4.zip)

## Week 5: Hypothesis Testing

* Lab files Lab 5 - Hypothesis Testing

## Week 6: Sampling Distribution

* Lab files Lab 6 - Sampling Distribution

## Week 7: Model Building

* Lab files: Lab 7 - Model Building