---
title: "Work Session 3 worksheet - regression interpretation"
author: "Student"
date: "1/25/2022"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(gridExtra)
library(knitr)

theme_set(theme_classic())

hurricanes <- read.csv("hurricanes.csv")
```

When you are finished, if you are not called on in the in-person lab, please write a two or three sentence summary of your results and post your best graph in the `#lecture-and-lab-chat` channel. If you worked with a partner, also tag your partner.

If you are a remote student, please plan on meeting with me during Friday office hours.

# Interpretation steps

## Interpretation goals

Interpreting the output of regression tables is an essential skill for a statistical analyst. Being able to tell if your regression coefficients indicate a meaningful relationship as well as reading the diagnostic information found in a regression table is key to model building and statistical literacy. We will develop these skills in three exercises.

* Learning objectives:
  + Practice interpreting slopes
  + Practice interpreting intercepts
  + Develop skills to understand statistical magnitude
  + Understand under what domains models are valid
  
## Interpretation process

These steps are steps that every statistical modeler should take when analyzing data.

1. Before starting, write a sentence or two on your expectation of the relationship – what direction will it be, how strongly will the two be related, and does the predictor variable have a large or small impact on the response variable.
2. What are the units of the predictor and response variable?
4. Draw a scatterplot of the relationship between the two variables. Does it appear that one variable needs to be reexpressed? If so, find the best reexpression possible (the data may not look very pretty even after reinterpretation, your goal is to make the relationship as linear as possible)
5. Conduct and view a regression. The general command is:

```
mod <- lm(data=<yourdata>, <response.variable> ~ <predictor.variable>)
summary(mod)
```

6. Interpret the slope of the regression line – does a large change in the predictor variable lead to a large or small change in the response variable?
7. What are reasonable values for the predictor variables? When would our best fit line have meaning and when would it not?
8. Interpret the intercept. Does it have meaning in this case?
9. Solve for the predicted value of the response variable at Q1 and Q3 of the predictor variable. Does moving from Q1 to Q3 of the predictor variable result in a large change (in your opinion) in the response variable?
10. Draw a box plot of the residuals based on the table. Does the boxplot suggest any problems? What are the units?
11. Interpret the residual standard error – how big or small is it? 
12. Interpret the $R^2$ - how much better is this model than the baseline model? What is the baseline model? Specifically, how much variance is this model explaining?
13. Based on the $R^2$, calculate the correlation coefficient, $r$. Do you consider that to be a large or small correlation based on your knowledge of the data?
14. What is some more information you’d like to know before making a final conclusion about the relationship between the two variables?

# Real data

## Hurricane Data

Variable definitions:

* `Name` - Hurricane name

* `Year` - Numeric

* `LF.WindsMPH` - Maximum sustained windspeed (>= 1 minute) to occur along the US coast. Prior to 1980, this is estimated from the maximum windspeed associated with the Saffir-Simpson index at landfall. If 2 or more landfalls, the maximum is taken

* `LF.PressureMB` - Atmospheric pressure at landfall in millibars. If 2 or more landfalls, the minimum is taken

* `LF.times` - Number of times the hurricane made landfall

* `BaseDamage` - Property damage (in millions of dollars for that year)

* `NDAM2014` - Damage, had hurricane appeared in 2014

* `AffectedStates` - Affected states (2-digit abbreviations), pasted together

* `firstLF` - Date of first landfall

* `deaths` - Number of continental US direct and indirect deaths

* `mf` - Gender of name

* `LF.WindsKPH` - Maximum sustained windspeed expressed in kilometers/hr

## Investigate

Using the 14 steps described above, investigate the relationship between two variables that you think should be related. 
